spring.application.name=hotel-booking

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

management.metrics.tags.application=hotel-booking
